# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: justdoit_development

test:
  <<: *default
  database: justdoit_test

production:
  <<: *default
  database: justdoit_production
